/**
 * The optional useless-knowledge corpus.
 *
 * Opt-in, off by default, and kept in its own file so it can never be confused
 * with the alcohol lines. Its purpose is different: those inform, these simply
 * occupy. During a craving the second job is as legitimate as the first — an
 * impatient mind given nothing to chew on will find the fridge.
 *
 * Everything here is written from scratch rather than lifted from a trivia site:
 * copying would mean someone else's licence and someone else's fact-checking,
 * and half of what circulates online as trivia is wrong. Where a popular claim
 * is a myth, the line says so instead of repeating it.
 *
 * Ids must stay stable — the rotation stores exposure against them.
 */

import type { Fact } from './facts';

export const TRIVIA: Fact[] = [
  { id: 't-1', category: 'trivia', text: 'Mesikäpälä eli hunajamäyrä pystyy kääntymään löysässä nahassaan ympäri, jos peto tarttuu siihen niskasta.' },
  { id: 't-2', category: 'trivia', text: 'Banaani on marja, mansikka ei ole.' },
  { id: 't-3', category: 'trivia', figure: 'octopus-hearts', text: 'Mustekalalla on kolme sydäntä ja sininen veri.' },
  { id: 't-4', category: 'trivia', text: 'Vombatin uloste on kuutionmuotoista.' },
  { id: 't-5', category: 'trivia', text: 'Kirahvin kaulassa on yhtä monta nikamaa kuin ihmisen: seitsemän.' },
  { id: 't-6', category: 'trivia', text: 'Merisiili kävelee hampaillaan.' },
  { id: 't-7', category: 'trivia', text: 'Kilpikonna hengittää osittain takapuolensa kautta.' },
  { id: 't-8', category: 'trivia', text: 'Napostelun aikana simpanssit käyttävät työkaluja, joita ne valmistavat itse etukäteen.' },
  { id: 't-9', category: 'trivia', text: 'Delfiinit nukkuvat puoli aivoa kerrallaan, jotta ne muistavat nousta hengittämään.' },
  { id: 't-10', category: 'trivia', text: 'Etanan suussa on kymmeniä tuhansia pieniä hampaita.' },
  { id: 't-11', category: 'trivia', text: 'Sudenkorento saalistaa onnistuneesti noin yhdeksän kertaa kymmenestä, mikä on eläinkunnan huippua.' },
  { id: 't-12', category: 'trivia', text: 'Merikilpikonnan sukupuoli määräytyy munan hautumislämpötilan mukaan.' },
  { id: 't-13', category: 'trivia', text: 'Kolibri on ainoa lintu joka osaa lentää taaksepäin.' },
  { id: 't-14', category: 'trivia', text: 'Naali vaihtaa turkkinsa värin kahdesti vuodessa.' },
  { id: 't-15', category: 'trivia', text: 'Tiikerillä on raidat myös ihossa, ei vain turkissa.' },
  { id: 't-16', category: 'trivia', text: 'Laiskiainen voi kääntää päätään noin 270 astetta.' },
  { id: 't-17', category: 'trivia', text: 'Kissalla on noin kaksisataa luuta, ihmisellä noin kaksisataakuusi.' },
  { id: 't-18', category: 'trivia', text: 'Koiran nenänjälki on yhtä yksilöllinen kuin ihmisen sormenjälki.' },
  { id: 't-19', category: 'trivia', text: 'Hylkeet voivat nukkua pystyasennossa veden alla.' },
  { id: 't-20', category: 'trivia', text: 'Muurahaisilla ei ole keuhkoja; happi kulkee kehon sivuilla olevista aukoista.' },
  { id: 't-21', category: 'trivia', text: 'Kuningatarmuurahainen voi elää yli kaksikymmentä vuotta.' },
  { id: 't-22', category: 'trivia', text: 'Krokotiili ei pysty työntämään kieltään ulos suustaan.' },
  { id: 't-23', category: 'trivia', text: 'Norsu on ainoa nisäkäs joka ei osaa hypätä.' },
  { id: 't-24', category: 'trivia', text: 'Sinivalaan sydän painaa satoja kiloja.' },
  { id: 't-25', category: 'trivia', text: 'Sinivalaan poikanen kasvaa ensimmäisenä vuotenaan noin yhdeksänkymmentä kiloa päivässä.' },
  { id: 't-26', category: 'trivia', text: 'Merileijonat osaavat pitää rytmiä musiikin tahdissa.' },
  { id: 't-27', category: 'trivia', text: 'Papukaijoista osa osaa liikkua musiikin tahdissa spontaanisti.' },
  { id: 't-28', category: 'trivia', text: 'Variksilla on kyky tunnistaa yksittäisiä ihmiskasvoja vuosien ajan.' },
  { id: 't-29', category: 'trivia', text: 'Varis osaa taivuttaa metallilangan koukuksi saadakseen ruokaa astian pohjalta.' },
  { id: 't-30', category: 'trivia', text: 'Hevonen ei pysty oksentamaan.' },
  { id: 't-31', category: 'trivia', text: 'Kameli ei varastoa kyhmyyn vettä vaan rasvaa.' },
  { id: 't-32', category: 'trivia', text: 'Kirahvin kieli on tummansininen, mikä suojaa sitä auringolta.' },
  { id: 't-33', category: 'trivia', text: 'Strutsin silmä on suurempi kuin sen aivot.' },
  { id: 't-34', category: 'trivia', text: 'Pingviinit kosiskelevat toisiaan joskus kivillä.' },
  { id: 't-35', category: 'trivia', text: 'Keisaripingviini voi sukeltaa yli viidensadan metrin syvyyteen.' },
  { id: 't-36', category: 'trivia', text: 'Jääkarhun iho on musta ja karvat ovat läpinäkyviä, eivät valkoisia.' },
  { id: 't-37', category: 'trivia', text: 'Sammakko ei juo vaan imee vettä ihonsa läpi.' },
  { id: 't-38', category: 'trivia', text: 'Aksolotli pystyy uudistamaan raajansa ja osia sydämestään.' },
  { id: 't-39', category: 'trivia', text: 'Merikorento vaihtaa väriään ympäristön mukaan sekunneissa.' },
  { id: 't-40', category: 'trivia', text: 'Mustekala pystyy livahtamaan minkä tahansa aukon läpi, joka on sen nokkaa suurempi.' },
  { id: 't-41', category: 'trivia', text: 'Hai ei sairastu juuri koskaan syöpään, mutta väite että se ei sairastu koskaan on virheellinen.' },
  { id: 't-42', category: 'trivia', text: 'Kalaparvi voi kääntyä yhtenä massana nopeammin kuin hermosignaali ehtii kulkea parven läpi.' },
  { id: 't-43', category: 'trivia', text: 'Ihmisen mahahappo pystyisi liuottamaan partakoneenterän, mutta limakalvo uusiutuu muutamassa päivässä.' },
  { id: 't-44', category: 'trivia', text: 'Ihmisen luuranko uusiutuu kokonaan noin kymmenessä vuodessa.' },
  { id: 't-45', category: 'trivia', text: 'Sylki tuottaa noin puolitoista litraa päivässä.' },
  { id: 't-46', category: 'trivia', text: 'Ihmisen silmä erottaa miljoonia värisävyjä.' },
  { id: 't-47', category: 'trivia', text: 'Aivot kuluttavat noin viidenneksen kaikesta energiasta, vaikka painavat vain pari prosenttia.' },
  { id: 't-48', category: 'trivia', text: 'Ihmisen suolisto sisältää enemmän bakteereita kuin galaksissa on tähtiä.' },
  { id: 't-49', category: 'trivia', text: 'Ihmisellä on jalkapohjassa enemmän hikirauhasia kuin missään muualla kehossa.' },
  { id: 't-50', category: 'trivia', text: 'Sormenjäljet muodostuvat jo kohdussa eivätkä muutu koskaan.' },
  { id: 't-51', category: 'trivia', text: 'Kaksosilla on erilaiset sormenjäljet.' },
  { id: 't-52', category: 'trivia', text: 'Ihmisen reisiluu kestää pystysuunnassa enemmän painoa kuin betoni samassa poikkipinta-alassa.' },
  { id: 't-53', category: 'trivia', text: 'Aivastuksen nopeus on kymmeniä kilometrejä tunnissa.' },
  { id: 't-54', category: 'trivia', text: 'Sydän lyö noin sata tuhatta kertaa vuorokaudessa.' },
  { id: 't-55', category: 'trivia', text: 'Ihminen menettää päivittäin miljoonia ihosoluja.' },
  { id: 't-56', category: 'trivia', text: 'Kyyneleet ovat kemialliselta koostumukseltaan erilaisia riippuen siitä, johtuvatko ne surusta, sipulista vai roskasta.' },
  { id: 't-57', category: 'trivia', text: 'Vatsalaukku ei kasva pysyvästi ruoasta, mutta se venyy hetkellisesti moninkertaiseksi.' },
  { id: 't-58', category: 'trivia', text: 'Ihminen ei voi niellä ja hengittää samaan aikaan.' },
  { id: 't-59', category: 'trivia', text: 'Maksa on ainoa ihmisen sisäelin joka kasvaa takaisin merkittävästi.' },
  { id: 't-60', category: 'trivia', text: 'Nenä ja korvat kasvavat läpi elämän, koska rusto ei lakkaa kasvamasta.' },
  { id: 't-61', category: 'trivia', text: 'Aikuisen ihmisen verisuonet olisivat peräkkäin yli satatuhatta kilometriä pitkät.' },
  { id: 't-62', category: 'trivia', text: 'Ihmisen sydän tuottaa tarpeeksi painetta suihkuttaakseen verta useita metrejä.' },
  { id: 't-63', category: 'trivia', text: 'Aivoilla itsellään ei ole kipureseptoreita.' },
  { id: 't-64', category: 'trivia', text: 'Yli puolet ihmisen kehon soluista ei ole ihmisen omia soluja.' },
  { id: 't-65', category: 'trivia', text: 'Kuun pinnalla jalanjäljet säilyvät miljoonia vuosia, koska tuulta ei ole.' },
  { id: 't-66', category: 'trivia', figure: 'moon-drift', text: 'Kuu loittonee Maasta muutaman senttimetrin vuodessa.' },
  { id: 't-67', category: 'trivia', text: 'Venuksen vuorokausi on pidempi kuin sen vuosi.' },
  { id: 't-68', category: 'trivia', text: 'Auringossa syntynyt valo voi kulkea sen sisäosista pintaan kymmeniä tuhansia vuosia.' },
  { id: 't-69', category: 'trivia', figure: 'light-travel', text: 'Auringonvalo saapuu Maahan noin kahdeksassa minuutissa.' },
  { id: 't-70', category: 'trivia', figure: 'saturn-float', text: 'Saturnuksen tiheys on niin pieni, että se kelluisi tarpeeksi suuressa vesialtaassa.' },
  { id: 't-71', category: 'trivia', text: 'Jupiterin suuri punainen pilkku on myrsky, joka on kestänyt satoja vuosia.' },
  { id: 't-72', category: 'trivia', text: 'Avaruudessa ei kuulu ääntä, koska ääni tarvitsee väliaineen.' },
  { id: 't-73', category: 'trivia', text: 'Neutronitähden teelusikallinen painaisi miljardeja tonneja.' },
  { id: 't-74', category: 'trivia', text: 'Maailmankaikkeudessa on enemmän tähtiä kuin Maan rannoilla hiekanjyviä.' },
  { id: 't-75', category: 'trivia', text: 'Marsin auringonlasku on sininen.' },
  { id: 't-76', category: 'trivia', text: 'Painovoima Kuussa on noin kuudesosa Maan painovoimasta.' },
  { id: 't-77', category: 'trivia', text: 'Kansainvälinen avaruusasema kiertää Maan noin puolessatoista tunnissa.' },
  { id: 't-78', category: 'trivia', text: 'Avaruudessa astronautit kasvavat muutaman senttimetrin, koska selkäranka ei purista kokoon.' },
  { id: 't-79', category: 'trivia', text: 'Kaukaisin ihmisen tekemä esine on Voyager 1, joka lähti matkaan vuonna 1977.' },
  { id: 't-80', category: 'trivia', text: 'Halleyn komeetta näkyy Maasta noin seitsemänkymmenenviiden vuoden välein.' },
  { id: 't-81', category: 'trivia', figure: 'ice-expand', text: 'Vesi on harvinaisen aine siinä, että se laajenee jäätyessään.' },
  { id: 't-82', category: 'trivia', text: 'Lasi ei ole nestettä, vaikka niin usein väitetään. Vanhojen ikkunoiden paksuuserot johtuvat valmistustavasta.' },
  { id: 't-83', category: 'trivia', text: 'Hunaja ei pilaannu. Egyptiläisistä haudoista löytynyt hunaja on yhä syömäkelpoista.' },
  { id: 't-84', category: 'trivia', text: 'Kuuma vesi voi jäätyä joissakin oloissa kylmää nopeammin. Ilmiötä kutsutaan Mpemban ilmiöksi.' },
  { id: 't-85', category: 'trivia', text: 'Kulta on niin taipuisaa, että yhdestä grammasta voi vetää yli kilometrin pituisen langan.' },
  { id: 't-86', category: 'trivia', text: 'Timantti ja lyijykynän grafiitti koostuvat molemmat pelkästä hiilestä.' },
  { id: 't-87', category: 'trivia', text: 'Helium on ainoa aine jota ei saa jähmettymään normaalipaineessa.' },
  { id: 't-88', category: 'trivia', text: 'Ilman happea rauta ei ruostu.' },
  { id: 't-89', category: 'trivia', text: 'Salama kuumentaa ilman hetkeksi moninkertaisesti Auringon pintaa kuumemmaksi.' },
  { id: 't-90', category: 'trivia', text: 'Ukkosen jyrinä on ilman räjähdysmäisen laajenemisen ääni.' },
  { id: 't-91', category: 'trivia', text: 'Vesi johtaa sähköä huonosti; sen sisältämät suolat johtavat.' },
  { id: 't-92', category: 'trivia', text: 'Bambu voi kasvaa lähes metrin vuorokaudessa.' },
  { id: 't-93', category: 'trivia', text: 'Maailman vanhin tunnettu puu on yli neljätuhatta vuotta vanha.' },
  { id: 't-94', category: 'trivia', text: 'Sienirihmasto voi olla maailman suurin yksittäinen eliö pinta-alaltaan.' },
  { id: 't-95', category: 'trivia', text: 'Ananas kasvaa maassa, ei puussa.' },
  { id: 't-96', category: 'trivia', text: 'Maapähkinä ei ole pähkinä vaan palkokasvi.' },
  { id: 't-97', category: 'trivia', text: 'Tomaatti on hedelmä, mutta USA:n korkein oikeus luokitteli sen tulliasiassa vihannekseksi.' },
  { id: 't-98', category: 'trivia', text: 'Chilin polttavuus ei ole makuaisti vaan kipureseptorin reaktio.' },
  { id: 't-99', category: 'trivia', text: 'Muskottipähkinä on suurina määrinä myrkyllistä.' },
  { id: 't-100', category: 'trivia', text: 'Kaneli tulee puun kuoresta.' },
  { id: 't-101', category: 'trivia', text: 'Sahrami on painonsa mukaan maailman kallein mauste, koska se poimitaan käsin kukan luotista.' },
  { id: 't-102', category: 'trivia', text: 'Vanilja on toiseksi kallein mauste ja tulee orkidean pavusta.' },
  { id: 't-103', category: 'trivia', text: 'Suklaa on koirille myrkyllistä teobromiinin takia.' },
  { id: 't-104', category: 'trivia', text: 'Kahvipapu ei ole papu vaan kirsikkamaisen marjan siemen.' },
  { id: 't-105', category: 'trivia', text: 'Porkkanat olivat alun perin useimmiten violetteja.' },
  { id: 't-106', category: 'trivia', text: 'Omena kelluu, koska siitä noin neljännes on ilmaa.' },
  { id: 't-107', category: 'trivia', figure: 'hexagons', text: 'Hunajakenno on kuusikulmainen, koska se on tehokkain tapa täyttää pinta ilman hukkaa.' },
  { id: 't-108', category: 'trivia', text: 'Eiffel-torni kasvaa kesällä noin viisitoista senttimetriä lämpölaajenemisen takia.' },
  { id: 't-109', category: 'trivia', text: 'Nykyään käytössä oleva QWERTY-näppäimistö suunniteltiin kirjoituskoneen mekaniikan ehdoilla.' },
  { id: 't-110', category: 'trivia', text: 'Ensimmäinen tietokonevirhe eli bug oli kirjaimellisesti perhonen releen välissä.' },
  { id: 't-111', category: 'trivia', text: 'Ensimmäinen verkkosivu on yhä olemassa CERNin palvelimella.' },
  { id: 't-112', category: 'trivia', text: 'Sähköpostia lähetettiin ennen kuin internetiä oli olemassa nykymuodossaan.' },
  { id: 't-113', category: 'trivia', text: 'Suomessa on enemmän saaria kuin missään muussa maassa.' },
  { id: 't-114', category: 'trivia', text: 'Suomen järviä on lähes kaksisataatuhatta.' },
  { id: 't-115', category: 'trivia', text: 'Suomen kieli ei tee eroa hänen ja sen välillä sukupuolen suhteen.' },
  { id: 't-116', category: 'trivia', text: 'Islannissa ei ole yhtään hyttystä.' },
  { id: 't-117', category: 'trivia', text: 'Vatikaani on maailman pienin valtio.' },
  { id: 't-118', category: 'trivia', text: 'Venäjä ulottuu yhdentoista aikavyöhykkeen yli.' },
  { id: 't-119', category: 'trivia', text: 'Australiassa on enemmän kenguruja kuin ihmisiä.' },
  { id: 't-120', category: 'trivia', text: 'Sahara oli muutama tuhat vuotta sitten vihreä savanni.' },
  { id: 't-121', category: 'trivia', text: 'Kuolleessameressä ei voi upota, koska suolapitoisuus tekee vedestä niin tiheää.' },
  { id: 't-122', category: 'trivia', text: 'Kuolleenmeren pinta laskee vuosittain noin metrin.' },
  { id: 't-123', category: 'trivia', text: 'Maailman korkein vesiputous Angelin putous Venezuelassa on lähes kilometrin korkuinen.' },
  { id: 't-124', category: 'trivia', text: 'Mount Everest kasvaa muutaman millimetrin vuodessa.' },
  { id: 't-125', category: 'trivia', text: 'Merenpohjasta on kartoitettu tarkemmin pienempi osa kuin Marsin pinnasta.' },
  { id: 't-126', category: 'trivia', text: 'Tyynellämerellä on syvänne, joka on syvempi kuin Everest on korkea.' },
  { id: 't-127', category: 'trivia', text: 'Antarktis on maailman suurin aavikko sademäärällä mitattuna.' },
  { id: 't-128', category: 'trivia', text: 'Grönlanti näyttää kartalla Afrikan kokoiselta, mutta Afrikka on noin neljätoistakertainen.' },
  { id: 't-129', category: 'trivia', text: 'Islanti ja Grönlanti on nimetty osapuilleen päinvastoin kuin niiden ilmasto edellyttäisi.' },
  { id: 't-130', category: 'trivia', text: 'Suomen lippu vahvistettiin nykyiseen muotoonsa vuonna 1918.' },
  { id: 't-131', category: 'trivia', text: 'Oxfordin yliopisto on vanhempi kuin atsteekkien valtakunta.' },
  { id: 't-132', category: 'trivia', text: 'Kleopatra eli lähemmäs Kuu-lentoa kuin pyramidien rakentamista.' },
  { id: 't-133', category: 'trivia', text: 'Mammutteja eli vielä silloin kun Egyptin pyramideja rakennettiin.' },
  { id: 't-134', category: 'trivia', text: 'Hai on ollut olemassa pidempään kuin puut.' },
  { id: 't-135', category: 'trivia', text: 'Tyrannosaurus eli lähempänä nykyaikaa kuin Stegosaurusta.' },
  { id: 't-136', category: 'trivia', text: 'Ranska teloitti viimeisen kerran giljotiinilla samana vuonna kun Tähtien sota sai ensi-iltansa.' },
  { id: 't-137', category: 'trivia', text: 'Nintendo perustettiin vuonna 1889 pelikorttiyhtiönä.' },
  { id: 't-138', category: 'trivia', text: 'Kaksi tuntia kestänyt sota Britannian ja Sansibarin välillä vuonna 1896 on lyhin tunnettu sota.' },
  { id: 't-139', category: 'trivia', text: 'Napoleon ei ollut aikalaistensa mittapuulla lyhyt.' },
  { id: 't-140', category: 'trivia', text: 'Vanhin tunnettu asiakasvalitus on kirjoitettu savitaululle noin 3700 vuotta sitten.' },
  { id: 't-141', category: 'trivia', text: 'Kirjoitustaito keksittiin useaan kertaan toisistaan riippumatta eri puolilla maailmaa.' },
  { id: 't-142', category: 'trivia', text: 'Nolla otettiin lukuna käyttöön paljon myöhemmin kuin muut numerot.' },
  { id: 't-143', category: 'trivia', text: 'Roomalaisilla ei ollut merkkiä nollalle.' },
  { id: 't-144', category: 'trivia', text: 'Sekunnin pituus määritellään nykyään cesiumatomin värähtelyn perusteella.' },
  { id: 't-145', category: 'trivia', text: 'Metri määriteltiin alun perin osana Maan meridiaanin pituutta.' },
  { id: 't-146', category: 'trivia', text: 'Kilogramman määritelmä perustuu nykyään luonnonvakioon eikä metallikappaleeseen.' },
  { id: 't-147', category: 'trivia', text: 'Miljardi tarkoitti Britanniassa pitkään eri lukua kuin Yhdysvalloissa.' },
  { id: 't-148', category: 'trivia', text: 'Sekoitetussa korttipakassa oleva järjestys ei todennäköisesti ole koskaan aiemmin esiintynyt.' },
  { id: 't-149', category: 'trivia', text: 'Syntymäpäiväparadoksi: 23 ihmisen joukossa on jo yli puolet mahdollisuus samalle syntymäpäivälle.' },
  { id: 't-150', category: 'trivia', figure: 'fold-double', text: 'Taitettu paperi ei käytännössä taitu yli kahdeksaa kertaa, koska paksuus kaksinkertaistuu joka kerta.' },
  { id: 't-151', category: 'trivia', text: 'Shakissa on enemmän mahdollisia pelejä kuin havaittavassa maailmankaikkeudessa atomeja.' },
  { id: 't-152', category: 'trivia', text: 'Kissan kehräämisen taajuus osuu alueelle, jonka on havaittu edistävän luun paranemista.' },
  { id: 't-153', category: 'trivia', text: 'Kissa ei maista makeaa; sen makureseptori on rikki.' },
  { id: 't-154', category: 'trivia', text: 'Koira hikoilee lähinnä käpälätyynyjen kautta.' },
  { id: 't-155', category: 'trivia', text: 'Norsu tunnistaa itsensä peilistä, minkä osaa vain harva laji.' },
  { id: 't-156', category: 'trivia', text: 'Harakat kuuluvat samaan pieneen joukkoon peilitestin läpäisijöitä.' },
  { id: 't-157', category: 'trivia', text: 'Papukaija voi elää yli kahdeksankymmentävuotiaaksi.' },
  { id: 't-158', category: 'trivia', text: 'Grönlanninhai voi elää yli kolmesataa vuotta ja tulee sukukypsäksi vasta noin sadan vuoden iässä.' },
  { id: 't-159', category: 'trivia', text: 'Kvahog-simpukka nimeltä Ming eli yli viisisataa vuotta.' },
  { id: 't-160', category: 'trivia', text: 'Meduusalaji Turritopsis dohrnii voi palautua takaisin nuoruusmuotoonsa.' },
  { id: 't-161', category: 'trivia', text: 'Tardigradi eli vesikarhu kestää avaruuden tyhjiön hetken aikaa.' },
  { id: 't-162', category: 'trivia', text: 'Kolibrin sydän lyö lennossa yli tuhat kertaa minuutissa.' },
  { id: 't-163', category: 'trivia', text: 'Päästäisen on syötävä lähes jatkuvasti tai se kuolee nälkään vuorokaudessa.' },
  { id: 't-164', category: 'trivia', text: 'Sinivalaan kieli painaa yhtä paljon kuin norsu.' },
  { id: 't-165', category: 'trivia', text: 'Valaan laulu voi kantaa satojen kilometrien päähän.' },
  { id: 't-166', category: 'trivia', text: 'Kaskelotin aivot ovat maailman suurimmat.' },
  { id: 't-167', category: 'trivia', text: 'Simpanssin lyhytkestoinen muisti voittaa ihmisen tietyissä numerotehtävissä.' },
  { id: 't-168', category: 'trivia', text: 'Mehiläinen tanssii pesässä kertoakseen muille ruoan suunnan ja etäisyyden.' },
  { id: 't-169', category: 'trivia', text: 'Mehiläinen tuottaa elinaikanaan noin kahdestoistaosan teelusikallista hunajaa.' },
  { id: 't-170', category: 'trivia', text: 'Muurahaisia on arviolta enemmän kuin kaksikymmentä kvadriljoonaa.' },
  { id: 't-171', category: 'trivia', text: 'Termiittien kekojen ilmanvaihto toimii ilman liikkuvia osia.' },
  { id: 't-172', category: 'trivia', text: 'Sudenkorento oli hiilikaudella siipiväliltään lähes metrin levyinen.' },
  { id: 't-173', category: 'trivia', text: 'Torakka voi elää viikkoja ilman päätä ja kuolee lopulta nälkään.' },
  { id: 't-174', category: 'trivia', text: 'Hyttynen valitsee kohteensa osittain hengityksen hiilidioksidin perusteella.' },
  { id: 't-175', category: 'trivia', text: 'Kirppu hyppää satakertaisesti oman pituutensa verran.' },
  { id: 't-176', category: 'trivia', text: 'Etana voi nukkua kolme vuotta yhtäjaksoisesti.' },
  { id: 't-177', category: 'trivia', text: 'Kameleontti ei vaihda väriä maastoutuakseen vaan viestiäkseen ja säädelläkseen lämpöä.' },
  { id: 't-178', category: 'trivia', text: 'Käärme haistaa kielellään ja tunnistaa hajun suunnan kielen kahdella kärjellä.' },
  { id: 't-179', category: 'trivia', text: 'Kobra ei kuule musiikkia vaan seuraa käärmeenlumoojan liikettä.' },
  { id: 't-180', category: 'trivia', text: 'Sammakkolajilla nimeltä puukiipijä on ihossaan yhden ihmisen tappava määrä myrkkyä.' },
  { id: 't-181', category: 'trivia', text: 'Merileijona ja hylje eroavat siitä, onko niillä ulkoiset korvalehdet.' },
  { id: 't-182', category: 'trivia', text: 'Valas on maalla eläneen nisäkkään jälkeläinen.' },
  { id: 't-183', category: 'trivia', text: 'Delfiini antaa toisilleen yksilöllisiä vihellyksiä, jotka toimivat niminä.' },
  { id: 't-184', category: 'trivia', text: 'Naaraslohi palaa kutemaan siihen jokeen, jossa se kuoriutui.' },
  { id: 't-185', category: 'trivia', text: 'Ankeriaan lisääntymistä ei ole koskaan havaittu luonnossa.' },
  { id: 't-186', category: 'trivia', text: 'Kalojen joukossa on lajeja, jotka vaihtavat sukupuolta elämänsä aikana.' },
  { id: 't-187', category: 'trivia', text: 'Merikrotti houkuttelee saalista valoa tuottavalla bakteerilla.' },
  { id: 't-188', category: 'trivia', text: 'Syvänmeren eläimistä valtaosa tuottaa itse valoa.' },
  { id: 't-189', category: 'trivia', text: 'Pingviini juo merivettä ja erittää suolan silmien yläpuolisten rauhasten kautta.' },
  { id: 't-190', category: 'trivia', text: 'Albatrossi voi liitää tuntikausia räpyttämättä siipiään.' },
  { id: 't-191', category: 'trivia', text: 'Tiira lentää elämänsä aikana etäisyyden, joka vastaa useaa Kuun edestakaista matkaa.' },
  { id: 't-192', category: 'trivia', text: 'Käki munii toisten lintujen pesiin eikä hoida poikasiaan.' },
  { id: 't-193', category: 'trivia', text: 'Kanan muna on yksi solu ennen hedelmöitystä.' },
  { id: 't-194', category: 'trivia', text: 'Strutsi voi juosta yli seitsemänkymmentä kilometriä tunnissa.' },
  { id: 't-195', category: 'trivia', text: 'Kiwi munii linnuista suhteellisesti suurimman munan kokoonsa nähden.' },
  { id: 't-196', category: 'trivia', text: 'Pöllön silmät eivät pyöri kuopissaan, minkä vuoksi sen on käännettävä koko päätään.' },
  { id: 't-197', category: 'trivia', text: 'Lepakko ei ole sokea, vaikka niin sanotaan.' },
  { id: 't-198', category: 'trivia', text: 'Lepakko on ainoa lentävä nisäkäs.' },
  { id: 't-199', category: 'trivia', text: 'Nokkaeläin munii ja tuottaa maitoa ilman nisiä.' },
  { id: 't-200', category: 'trivia', text: 'Nokkaeläimen uroksella on myrkkykannus takaraajassa.' },
  { id: 't-201', category: 'trivia', text: 'Kenguru ei pysty kävelemään taaksepäin.' },
  { id: 't-202', category: 'trivia', text: 'Koalan sormenjäljet muistuttavat ihmisen sormenjälkiä niin paljon, että ne voi sekoittaa.' },
  { id: 't-203', category: 'trivia', text: 'Vompatti pystyy juoksemaan hetkellisesti nopeammin kuin ihminen.' },
  { id: 't-204', category: 'trivia', text: 'Sarvikuonon sarvi koostuu keratiinista, samasta aineesta kuin kynnet.' },
  { id: 't-205', category: 'trivia', text: 'Virtahepo tuottaa punertavaa eritettä, joka toimii aurinkosuojana.' },
  { id: 't-206', category: 'trivia', text: 'Seepran raidat ovat todennäköisesti myös hyönteispuolustus.' },
  { id: 't-207', category: 'trivia', text: 'Kirahvi nukkuu muutaman minuutin kerrallaan.' },
  { id: 't-208', category: 'trivia', text: 'Laiskiaisen ruoansulatus voi kestää kuukauden.' },
  { id: 't-209', category: 'trivia', text: 'Panda syö bambua, vaikka sen ruoansulatus on lihansyöjän.' },
  { id: 't-210', category: 'trivia', text: 'Jääkarhun maksassa on niin paljon A-vitamiinia, että se on ihmiselle myrkyllistä.' },
  { id: 't-211', category: 'trivia', text: 'Ihmisen aivot eivät tunne kipua, mutta päänsärky syntyy ympäröivistä kudoksista.' },
  { id: 't-212', category: 'trivia', text: 'Ihmisen sydän jatkaa lyömistä hetken kehon ulkopuolella, koska sillä on oma tahdistin.' },
  { id: 't-213', category: 'trivia', text: 'Vasen keuhko on oikeaa pienempi, koska sydän vie tilaa.' },
  { id: 't-214', category: 'trivia', text: 'Ihminen erottaa yli biljoona hajua eri arvioiden mukaan.' },
  { id: 't-215', category: 'trivia', text: 'Nenä väsyy hajuun muutamassa minuutissa eikä enää havaitse sitä.' },
  { id: 't-216', category: 'trivia', text: 'Ihmisen silmä liikkuu unessa REM-vaiheessa, mistä vaihe on saanut nimensä.' },
  { id: 't-217', category: 'trivia', text: 'Aivot ovat unen aikana paikoin aktiivisempia kuin valveilla.' },
  { id: 't-218', category: 'trivia', text: 'Nukkuessa selkäranka pitenee, joten aamulla ihminen on hieman pidempi kuin illalla.' },
  { id: 't-219', category: 'trivia', text: 'Kaksi kolmasosaa ihmisistä kallistaa päätään oikealle suudellessaan.' },
  { id: 't-220', category: 'trivia', text: 'Ihmisen kädessä on 27 luuta.' },
  { id: 't-221', category: 'trivia', text: 'Peukalolla on oma lihaksisto, jota muilla sormilla ei ole.' },
  { id: 't-222', category: 'trivia', text: 'Kynnet kasvavat nopeammin kädessä kuin jalassa.' },
  { id: 't-223', category: 'trivia', text: 'Hiukset kasvavat noin senttimetrin kuukaudessa.' },
  { id: 't-224', category: 'trivia', text: 'Ihmisen kehossa on rautaa noin naulan verran.' },
  { id: 't-225', category: 'trivia', text: 'Ihmisen luut ovat painoonsa nähden vahvempia kuin teräs.' },
  { id: 't-226', category: 'trivia', text: 'Vauvalla on enemmän luita kuin aikuisella, koska osa luutuu yhteen.' },
  { id: 't-227', category: 'trivia', text: 'Vauva ei tuota kyyneleitä ensimmäisinä viikkoina.' },
  { id: 't-228', category: 'trivia', text: 'Ihmisen näkökenttä ulottuu lähes kahteensataan asteeseen.' },
  { id: 't-229', category: 'trivia', text: 'Silmä havaitsee yksittäisen fotonin sopivissa oloissa.' },
  { id: 't-230', category: 'trivia', text: 'Ihminen räpäyttää silmiään noin viisitoista kertaa minuutissa.' },
  { id: 't-231', category: 'trivia', text: 'Aivastaessa silmät sulkeutuvat refleksinomaisesti.' },
  { id: 't-232', category: 'trivia', text: 'Ihmisen korvat ja nenä eivät lakkaa kasvamasta.' },
  { id: 't-233', category: 'trivia', text: 'Sormien ryppyyntyminen vedessä on aktiivinen hermoston ohjaama reaktio, ei turpoamista.' },
  { id: 't-234', category: 'trivia', text: 'Kaksosista noin joka kolmas pari on identtinen.' },
  { id: 't-235', category: 'trivia', text: 'Ihmisellä on kaikilla vielä alkiovaiheessa häntä, joka häviää kehityksen aikana.' },
  { id: 't-236', category: 'trivia', text: 'Aikuisen ihmisen luuytimessä syntyy joka sekunti miljoonia uusia verisoluja.' },
  { id: 't-237', category: 'trivia', text: 'Auringon massa on yli 99 prosenttia koko aurinkokunnan massasta.' },
  { id: 't-238', category: 'trivia', text: 'Aurinko kiertää Linnunradan keskustan noin 230 miljoonassa vuodessa.' },
  { id: 't-239', category: 'trivia', text: 'Linnunrata ja Andromeda törmäävät noin neljän miljardin vuoden kuluttua.' },
  { id: 't-240', category: 'trivia', text: 'Mustan aukon tapahtumahorisontista ei pääse pois edes valo.' },
  { id: 't-241', category: 'trivia', text: 'Ensimmäinen kuva mustasta aukosta julkaistiin vuonna 2019.' },
  { id: 't-242', category: 'trivia', text: 'Avaruusromua kiertää Maata satoja tuhansia kappaleita.' },
  { id: 't-243', category: 'trivia', text: 'Kansainvälisellä avaruusasemalla nähdään kuusitoista auringonnousua vuorokaudessa.' },
  { id: 't-244', category: 'trivia', text: 'Astronautin pituus palautuu ennalleen muutamassa kuukaudessa paluun jälkeen.' },
  { id: 't-245', category: 'trivia', text: 'Painottomuudessa kyyneleet eivät valu vaan jäävät palloksi silmän päälle.' },
  { id: 't-246', category: 'trivia', text: 'Kuun pinnalla on nyt satoja kiloja ihmisen jättämää tavaraa.' },
  { id: 't-247', category: 'trivia', text: 'Kuun pöly haisee astronauttien mukaan ruudilta.' },
  { id: 't-248', category: 'trivia', text: 'Marsissa on aurinkokunnan korkein tunnettu tulivuori, Olympus Mons.' },
  { id: 't-249', category: 'trivia', text: 'Venuksen pintapaine vastaa lähes kilometrin syvyyttä meressä.' },
  { id: 't-250', category: 'trivia', text: 'Merkuriuksen vuorokausi kestää lähes kaksi sen omaa vuotta.' },
  { id: 't-251', category: 'trivia', text: 'Uranus kiertää kyljellään, akseli lähes kiertoradan tasossa.' },
  { id: 't-252', category: 'trivia', text: 'Neptunuksella tuulet ovat aurinkokunnan nopeimmat.' },
  { id: 't-253', category: 'trivia', text: 'Pluton kuu Kharon on niin suuri suhteessa Plutoon, että ne kiertävät yhteistä painopistettä.' },
  { id: 't-254', category: 'trivia', text: 'Auringonpimennys on mahdollinen vain koska Kuu ja Aurinko näyttävät taivaalla lähes samankokoisilta.' },
  { id: 't-255', category: 'trivia', text: 'Se yhteensattuma on väliaikainen: Kuun loitotessa täydelliset pimennykset loppuvat aikanaan.' },
  { id: 't-256', category: 'trivia', text: 'Maapallon magneettikenttä on kääntynyt satoja kertoja historian aikana.' },
  { id: 't-257', category: 'trivia', text: 'Maan pyöriminen hidastuu, ja vuorokausi pitenee erittäin hitaasti.' },
  { id: 't-258', category: 'trivia', text: 'Dinosaurusten aikaan vuorokausi oli lyhyempi kuin nyt.' },
  { id: 't-259', category: 'trivia', text: 'Maan sisin ydin on kiinteä, vaikka se on kuumempi kuin ulompi sula ydin.' },
  { id: 't-260', category: 'trivia', text: 'Suurin osa Maan hapesta tuotetaan meressä, ei metsissä.' },
  { id: 't-261', category: 'trivia', text: 'Sademetsää kutsutaan maapallon keuhkoiksi, mutta se kuluttaa lähes yhtä paljon happea kuin tuottaa.' },
  { id: 't-262', category: 'trivia', text: 'Amazon saa merkittävän osan lannoitteestaan Saharan pölystä.' },
  { id: 't-263', category: 'trivia', text: 'Maailman kuivimmassa paikassa Atacamassa on kohtia, joissa sadetta ei ole mitattu.' },
  { id: 't-264', category: 'trivia', text: 'Maapallon vedestä alle prosentti on helposti käytettävää makeaa vettä.' },
  { id: 't-265', category: 'trivia', text: 'Kaikki maapallon vesi mahtuisi palloon, jonka halkaisija olisi noin 1400 kilometriä.' },
  { id: 't-266', category: 'trivia', text: 'Yksi salamanisku sisältää energiaa, joka riittäisi valaisemaan hehkulampun kuukausiksi.' },
  { id: 't-267', category: 'trivia', text: 'Sateenkaari on todellisuudessa täysi ympyrä, josta maa peittää alaosan.' },
  { id: 't-268', category: 'trivia', text: 'Lumihiutaleet ovat lähes aina kuusisakaraisia veden molekyylirakenteen takia.' },
  { id: 't-269', category: 'trivia', text: 'Pohjoisnavalla ei ole aikavyöhykettä.' },
  { id: 't-270', category: 'trivia', text: 'Merivesi jäätyy alemmassa lämpötilassa kuin makea vesi.' },
  { id: 't-271', category: 'trivia', text: 'Merenpinnan alla on jokia: suolaisempaa vettä virtaamassa vähemmän suolaisen alla.' },
  { id: 't-272', category: 'trivia', text: 'Islannissa on käytössä nimilaki, joka rajoittaa uusien etunimien käyttöä.' },
  { id: 't-273', category: 'trivia', text: 'Suomen kielessä on viisitoista sijamuotoa.' },
  { id: 't-274', category: 'trivia', text: 'Kiinan kielessä ei ole aakkosia vaan tuhansia merkkejä.' },
  { id: 't-275', category: 'trivia', text: 'Sanskritin kielioppi kuvattiin niin tarkasti jo yli kaksituhatta vuotta sitten, että sitä käytetään yhä esimerkkinä.' },
  { id: 't-276', category: 'trivia', text: 'Islannin kieli on muuttunut niin vähän, että nykyislantilainen voi lukea tuhat vuotta vanhoja tekstejä.' },
  { id: 't-277', category: 'trivia', text: 'Baskin kieli ei ole sukua millekään tunnetulle kielelle.' },
  { id: 't-278', category: 'trivia', text: 'Maailmassa puhutaan yli seitsemäätuhatta kieltä, ja niistä huomattava osa on katoamassa.' },
  { id: 't-279', category: 'trivia', text: 'Aakkoset kehittyivät alun perin foinikialaisten kauppiaiden merkeistä.' },
  { id: 't-280', category: 'trivia', text: 'Kirjapaino keksittiin Kiinassa vuosisatoja ennen Gutenbergia.' },
  { id: 't-281', category: 'trivia', text: 'Paperi keksittiin Kiinassa, ja tieto siitä kulki länteen satojen vuosien viiveellä.' },
  { id: 't-282', category: 'trivia', text: 'Kirjastolla Aleksandriassa ei ollut yhtä tuhoa vaan useita, ja se hiipui vähitellen.' },
  { id: 't-283', category: 'trivia', text: 'Rooman betoni kovettui merivedessä ja on kestänyt kaksituhatta vuotta.' },
  { id: 't-284', category: 'trivia', text: 'Rooman valtakunnan tiestö oli niin hyvä, että osa reiteistä on yhä käytössä.' },
  { id: 't-285', category: 'trivia', text: 'Vikingit saapuivat Pohjois-Amerikkaan noin viisisataa vuotta ennen Kolumbusta.' },
  { id: 't-286', category: 'trivia', text: 'Kolumbus ei koskaan astunut nykyisen Yhdysvaltain maaperälle.' },
  { id: 't-287', category: 'trivia', text: 'Australian alkuperäiskansojen kulttuuri on maailman vanhin yhtäjaksoisesti jatkunut.' },
  { id: 't-288', category: 'trivia', text: 'Suuri Kiinan muuri ei näy avaruudesta paljaalla silmällä.' },
  { id: 't-289', category: 'trivia', text: 'Pyramidit rakennettiin palkatuilla työläisillä, ei orjilla.' },
  { id: 't-290', category: 'trivia', text: 'Napoleonin armeijan tuho Venäjällä johtui enemmän taudeista ja kylmästä kuin taisteluista.' },
  { id: 't-291', category: 'trivia', text: 'Ensimmäinen maailmansota päättyi sopimukseen, jonka korvaukset Saksa maksoi loppuun vasta 2010.' },
  { id: 't-292', category: 'trivia', text: 'Titanicin uppoamisesta selvisi noin kolmasosa matkustajista.' },
  { id: 't-293', category: 'trivia', text: 'Kuuhun laskeutumisen tietokoneessa oli vähemmän muistia kuin nykyisessä laskimessa.' },
  { id: 't-294', category: 'trivia', text: 'Ensimmäinen tekstiviesti lähetettiin vuonna 1992 ja siinä luki "Merry Christmas".' },
  { id: 't-295', category: 'trivia', text: 'Ensimmäinen verkkokaupasta ostettu tuote oli eri lähteiden mukaan joko levy tai pizza.' },
  { id: 't-296', category: 'trivia', text: 'Sähköauto keksittiin ennen polttomoottoriautoa.' },
  { id: 't-297', category: 'trivia', text: 'Faksi on vanhempi keksintö kuin puhelin.' },
  { id: 't-298', category: 'trivia', text: 'Mikroaaltouuni keksittiin sattumalta, kun tutkijan taskussa oleva suklaapatukka suli.' },
  { id: 't-299', category: 'trivia', text: 'Post-it-lapun liima syntyi epäonnistuneesta yrityksestä tehdä vahvaa liimaa.' },
  { id: 't-300', category: 'trivia', text: 'Penisilliini löytyi unohtuneesta maljasta.' },
  { id: 't-301', category: 'trivia', text: 'Teflon, sydämentahdistin ja turvalasi ovat kaikki syntyneet vahingossa.' },
  { id: 't-302', category: 'trivia', text: 'Salaman todennäköisyys osua samaan paikkaan kahdesti on suurempi kuin sanonta antaa ymmärtää.' },
  { id: 't-303', category: 'trivia', text: 'Kolikonheitto ei ole täysin tasapuolinen: heitetty kolikko putoaa hieman useammin samalle puolelle jolta se lähti.' },
  { id: 't-304', category: 'trivia', text: 'Monty Hallin ongelmassa oven vaihtaminen kaksinkertaistaa voittomahdollisuuden.' },
  { id: 't-305', category: 'trivia', text: 'Benfordin laki: luonnollisissa lukuaineistoissa ykkönen on ensimmäisenä numerona useammin kuin muut.' },
  { id: 't-306', category: 'trivia', text: 'Sitä käytetään kirjanpidon väärennösten etsimiseen.' },
  { id: 't-307', category: 'trivia', text: 'Pi on laskettu jo yli sadan biljoonan desimaalin tarkkuudella, vaikka avaruusnavigointiin riittää kymmenkunta.' },
  { id: 't-308', category: 'trivia', text: 'Nolla jaettuna nollalla ei ole määritelty, mutta raja-arvona se voi olla mitä tahansa.' },
  { id: 't-309', category: 'trivia', text: 'Äärettömiä on eri kokoisia, ja se on todistettu.' },
  { id: 't-310', category: 'trivia', text: 'Kaikkien luonnollisten lukujen summaa käytetään fysiikassa muodossa, joka näyttää olevan miinus yksi kahdestoistaosa.' },
  { id: 't-311', category: 'trivia', text: 'Neljä väriä riittää värittämään minkä tahansa kartan niin, ettei kahdella naapurilla ole samaa väriä.' },
  { id: 't-312', category: 'trivia', text: 'Sen todistus oli ensimmäinen merkittävä, joka vaati tietokonetta.' },
];
