/**
 * The optional useless-knowledge corpus.
 *
 * Opt-in, off by default, and kept in its own file so it can never be confused
 * with the alcohol lines. Its purpose is different: those inform, these simply
 * occupy. During a craving the second job is as legitimate as the first — an
 * impatient mind given nothing to chew on will find the fridge.
 *
 * Everything here is written from scratch rather than lifted from a trivia site:
 * copying would mean someone else's licence and someone else's fact-checking,
 * and half of what circulates online as trivia is wrong. Where a popular claim
 * is a myth, the line says so instead of repeating it.
 *
 * Ids must stay stable — the rotation stores exposure against them.
 */

import type { Fact } from './facts';

export const TRIVIA: Fact[] = [
  { id: 't-1', category: 'trivia', text: 'Mesikäpälä eli hunajamäyrä pystyy kääntymään löysässä nahassaan ympäri, jos peto tarttuu siihen niskasta.' },
  { id: 't-2', category: 'trivia', text: 'Banaani on marja, mansikka ei ole.' },
  { id: 't-3', category: 'trivia', text: 'Mustekalalla on kolme sydäntä ja sininen veri.' },
  { id: 't-4', category: 'trivia', text: 'Vombatin uloste on kuutionmuotoista.' },
  { id: 't-5', category: 'trivia', text: 'Kirahvin kaulassa on yhtä monta nikamaa kuin ihmisen: seitsemän.' },
  { id: 't-6', category: 'trivia', text: 'Merisiili kävelee hampaillaan.' },
  { id: 't-7', category: 'trivia', text: 'Kilpikonna hengittää osittain takapuolensa kautta.' },
  { id: 't-8', category: 'trivia', text: 'Napostelun aikana simpanssit käyttävät työkaluja, joita ne valmistavat itse etukäteen.' },
  { id: 't-9', category: 'trivia', text: 'Delfiinit nukkuvat puoli aivoa kerrallaan, jotta ne muistavat nousta hengittämään.' },
  { id: 't-10', category: 'trivia', text: 'Etanan suussa on kymmeniä tuhansia pieniä hampaita.' },
  { id: 't-11', category: 'trivia', text: 'Sudenkorento saalistaa onnistuneesti noin yhdeksän kertaa kymmenestä, mikä on eläinkunnan huippua.' },
  { id: 't-12', category: 'trivia', text: 'Merikilpikonnan sukupuoli määräytyy munan hautumislämpötilan mukaan.' },
  { id: 't-13', category: 'trivia', text: 'Kolibri on ainoa lintu joka osaa lentää taaksepäin.' },
  { id: 't-14', category: 'trivia', text: 'Naali vaihtaa turkkinsa värin kahdesti vuodessa.' },
  { id: 't-15', category: 'trivia', text: 'Tiikerillä on raidat myös ihossa, ei vain turkissa.' },
  { id: 't-16', category: 'trivia', text: 'Laiskiainen voi kääntää päätään noin 270 astetta.' },
  { id: 't-17', category: 'trivia', text: 'Kissalla on noin kaksisataa luuta, ihmisellä noin kaksisataakuusi.' },
  { id: 't-18', category: 'trivia', text: 'Koiran nenänjälki on yhtä yksilöllinen kuin ihmisen sormenjälki.' },
  { id: 't-19', category: 'trivia', text: 'Hylkeet voivat nukkua pystyasennossa veden alla.' },
  { id: 't-20', category: 'trivia', text: 'Muurahaisilla ei ole keuhkoja; happi kulkee kehon sivuilla olevista aukoista.' },
  { id: 't-21', category: 'trivia', text: 'Kuningatarmuurahainen voi elää yli kaksikymmentä vuotta.' },
  { id: 't-22', category: 'trivia', text: 'Krokotiili ei pysty työntämään kieltään ulos suustaan.' },
  { id: 't-23', category: 'trivia', text: 'Norsu on ainoa nisäkäs joka ei osaa hypätä.' },
  { id: 't-24', category: 'trivia', text: 'Sinivalaan sydän painaa satoja kiloja.' },
  { id: 't-25', category: 'trivia', text: 'Sinivalaan poikanen kasvaa ensimmäisenä vuotenaan noin yhdeksänkymmentä kiloa päivässä.' },
  { id: 't-26', category: 'trivia', text: 'Merileijonat osaavat pitää rytmiä musiikin tahdissa.' },
  { id: 't-27', category: 'trivia', text: 'Papukaijoista osa osaa liikkua musiikin tahdissa spontaanisti.' },
  { id: 't-28', category: 'trivia', text: 'Variksilla on kyky tunnistaa yksittäisiä ihmiskasvoja vuosien ajan.' },
  { id: 't-29', category: 'trivia', text: 'Varis osaa taivuttaa metallilangan koukuksi saadakseen ruokaa astian pohjalta.' },
  { id: 't-30', category: 'trivia', text: 'Hevonen ei pysty oksentamaan.' },
  { id: 't-31', category: 'trivia', text: 'Kameli ei varastoa kyhmyyn vettä vaan rasvaa.' },
  { id: 't-32', category: 'trivia', text: 'Kirahvin kieli on tummansininen, mikä suojaa sitä auringolta.' },
  { id: 't-33', category: 'trivia', text: 'Strutsin silmä on suurempi kuin sen aivot.' },
  { id: 't-34', category: 'trivia', text: 'Pingviinit kosiskelevat toisiaan joskus kivillä.' },
  { id: 't-35', category: 'trivia', text: 'Keisaripingviini voi sukeltaa yli viidensadan metrin syvyyteen.' },
  { id: 't-36', category: 'trivia', text: 'Jääkarhun iho on musta ja karvat ovat läpinäkyviä, eivät valkoisia.' },
  { id: 't-37', category: 'trivia', text: 'Sammakko ei juo vaan imee vettä ihonsa läpi.' },
  { id: 't-38', category: 'trivia', text: 'Aksolotli pystyy uudistamaan raajansa ja osia sydämestään.' },
  { id: 't-39', category: 'trivia', text: 'Merikorento vaihtaa väriään ympäristön mukaan sekunneissa.' },
  { id: 't-40', category: 'trivia', text: 'Mustekala pystyy livahtamaan minkä tahansa aukon läpi, joka on sen nokkaa suurempi.' },
  { id: 't-41', category: 'trivia', text: 'Hai ei sairastu juuri koskaan syöpään, mutta väite että se ei sairastu koskaan on virheellinen.' },
  { id: 't-42', category: 'trivia', text: 'Kalaparvi voi kääntyä yhtenä massana nopeammin kuin hermosignaali ehtii kulkea parven läpi.' },
  { id: 't-43', category: 'trivia', text: 'Ihmisen mahahappo pystyisi liuottamaan partakoneenterän, mutta limakalvo uusiutuu muutamassa päivässä.' },
  { id: 't-44', category: 'trivia', text: 'Ihmisen luuranko uusiutuu kokonaan noin kymmenessä vuodessa.' },
  { id: 't-45', category: 'trivia', text: 'Sylki tuottaa noin puolitoista litraa päivässä.' },
  { id: 't-46', category: 'trivia', text: 'Ihmisen silmä erottaa miljoonia värisävyjä.' },
  { id: 't-47', category: 'trivia', text: 'Aivot kuluttavat noin viidenneksen kaikesta energiasta, vaikka painavat vain pari prosenttia.' },
  { id: 't-48', category: 'trivia', text: 'Ihmisen suolisto sisältää enemmän bakteereita kuin galaksissa on tähtiä.' },
  { id: 't-49', category: 'trivia', text: 'Ihmisellä on jalkapohjassa enemmän hikirauhasia kuin missään muualla kehossa.' },
  { id: 't-50', category: 'trivia', text: 'Sormenjäljet muodostuvat jo kohdussa eivätkä muutu koskaan.' },
  { id: 't-51', category: 'trivia', text: 'Kaksosilla on erilaiset sormenjäljet.' },
  { id: 't-52', category: 'trivia', text: 'Ihmisen reisiluu kestää pystysuunnassa enemmän painoa kuin betoni samassa poikkipinta-alassa.' },
  { id: 't-53', category: 'trivia', text: 'Aivastuksen nopeus on kymmeniä kilometrejä tunnissa.' },
  { id: 't-54', category: 'trivia', text: 'Sydän lyö noin sata tuhatta kertaa vuorokaudessa.' },
  { id: 't-55', category: 'trivia', text: 'Ihminen menettää päivittäin miljoonia ihosoluja.' },
  { id: 't-56', category: 'trivia', text: 'Kyyneleet ovat kemialliselta koostumukseltaan erilaisia riippuen siitä, johtuvatko ne surusta, sipulista vai roskasta.' },
  { id: 't-57', category: 'trivia', text: 'Vatsalaukku ei kasva pysyvästi ruoasta, mutta se venyy hetkellisesti moninkertaiseksi.' },
  { id: 't-58', category: 'trivia', text: 'Ihminen ei voi niellä ja hengittää samaan aikaan.' },
  { id: 't-59', category: 'trivia', text: 'Maksa on ainoa ihmisen sisäelin joka kasvaa takaisin merkittävästi.' },
  { id: 't-60', category: 'trivia', text: 'Nenä ja korvat kasvavat läpi elämän, koska rusto ei lakkaa kasvamasta.' },
  { id: 't-61', category: 'trivia', text: 'Aikuisen ihmisen verisuonet olisivat peräkkäin yli satatuhatta kilometriä pitkät.' },
  { id: 't-62', category: 'trivia', text: 'Ihmisen sydän tuottaa tarpeeksi painetta suihkuttaakseen verta useita metrejä.' },
  { id: 't-63', category: 'trivia', text: 'Aivoilla itsellään ei ole kipureseptoreita.' },
  { id: 't-64', category: 'trivia', text: 'Yli puolet ihmisen kehon soluista ei ole ihmisen omia soluja.' },
  { id: 't-65', category: 'trivia', text: 'Kuun pinnalla jalanjäljet säilyvät miljoonia vuosia, koska tuulta ei ole.' },
  { id: 't-66', category: 'trivia', text: 'Kuu loittonee Maasta muutaman senttimetrin vuodessa.' },
  { id: 't-67', category: 'trivia', text: 'Venuksen vuorokausi on pidempi kuin sen vuosi.' },
  { id: 't-68', category: 'trivia', text: 'Auringossa syntynyt valo voi kulkea sen sisäosista pintaan kymmeniä tuhansia vuosia.' },
  { id: 't-69', category: 'trivia', text: 'Auringonvalo saapuu Maahan noin kahdeksassa minuutissa.' },
  { id: 't-70', category: 'trivia', text: 'Saturnuksen tiheys on niin pieni, että se kelluisi tarpeeksi suuressa vesialtaassa.' },
  { id: 't-71', category: 'trivia', text: 'Jupiterin suuri punainen pilkku on myrsky, joka on kestänyt satoja vuosia.' },
  { id: 't-72', category: 'trivia', text: 'Avaruudessa ei kuulu ääntä, koska ääni tarvitsee väliaineen.' },
  { id: 't-73', category: 'trivia', text: 'Neutronitähden teelusikallinen painaisi miljardeja tonneja.' },
  { id: 't-74', category: 'trivia', text: 'Maailmankaikkeudessa on enemmän tähtiä kuin Maan rannoilla hiekanjyviä.' },
  { id: 't-75', category: 'trivia', text: 'Marsin auringonlasku on sininen.' },
  { id: 't-76', category: 'trivia', text: 'Painovoima Kuussa on noin kuudesosa Maan painovoimasta.' },
  { id: 't-77', category: 'trivia', text: 'Kansainvälinen avaruusasema kiertää Maan noin puolessatoista tunnissa.' },
  { id: 't-78', category: 'trivia', text: 'Avaruudessa astronautit kasvavat muutaman senttimetrin, koska selkäranka ei purista kokoon.' },
  { id: 't-79', category: 'trivia', text: 'Kaukaisin ihmisen tekemä esine on Voyager 1, joka lähti matkaan vuonna 1977.' },
  { id: 't-80', category: 'trivia', text: 'Halleyn komeetta näkyy Maasta noin seitsemänkymmenenviiden vuoden välein.' },
  { id: 't-81', category: 'trivia', text: 'Vesi on harvinaisen aine siinä, että se laajenee jäätyessään.' },
  { id: 't-82', category: 'trivia', text: 'Lasi ei ole nestettä, vaikka niin usein väitetään. Vanhojen ikkunoiden paksuuserot johtuvat valmistustavasta.' },
  { id: 't-83', category: 'trivia', text: 'Hunaja ei pilaannu. Egyptiläisistä haudoista löytynyt hunaja on yhä syömäkelpoista.' },
  { id: 't-84', category: 'trivia', text: 'Kuuma vesi voi jäätyä joissakin oloissa kylmää nopeammin. Ilmiötä kutsutaan Mpemban ilmiöksi.' },
  { id: 't-85', category: 'trivia', text: 'Kulta on niin taipuisaa, että yhdestä grammasta voi vetää yli kilometrin pituisen langan.' },
  { id: 't-86', category: 'trivia', text: 'Timantti ja lyijykynän grafiitti koostuvat molemmat pelkästä hiilestä.' },
  { id: 't-87', category: 'trivia', text: 'Helium on ainoa aine jota ei saa jähmettymään normaalipaineessa.' },
  { id: 't-88', category: 'trivia', text: 'Ilman happea rauta ei ruostu.' },
  { id: 't-89', category: 'trivia', text: 'Salama kuumentaa ilman hetkeksi moninkertaisesti Auringon pintaa kuumemmaksi.' },
  { id: 't-90', category: 'trivia', text: 'Ukkosen jyrinä on ilman räjähdysmäisen laajenemisen ääni.' },
  { id: 't-91', category: 'trivia', text: 'Vesi johtaa sähköä huonosti; sen sisältämät suolat johtavat.' },
  { id: 't-92', category: 'trivia', text: 'Bambu voi kasvaa lähes metrin vuorokaudessa.' },
  { id: 't-93', category: 'trivia', text: 'Maailman vanhin tunnettu puu on yli neljätuhatta vuotta vanha.' },
  { id: 't-94', category: 'trivia', text: 'Sienirihmasto voi olla maailman suurin yksittäinen eliö pinta-alaltaan.' },
  { id: 't-95', category: 'trivia', text: 'Ananas kasvaa maassa, ei puussa.' },
  { id: 't-96', category: 'trivia', text: 'Maapähkinä ei ole pähkinä vaan palkokasvi.' },
  { id: 't-97', category: 'trivia', text: 'Tomaatti on hedelmä, mutta USA:n korkein oikeus luokitteli sen tulliasiassa vihannekseksi.' },
  { id: 't-98', category: 'trivia', text: 'Chilin polttavuus ei ole makuaisti vaan kipureseptorin reaktio.' },
  { id: 't-99', category: 'trivia', text: 'Muskottipähkinä on suurina määrinä myrkyllistä.' },
  { id: 't-100', category: 'trivia', text: 'Kaneli tulee puun kuoresta.' },
  { id: 't-101', category: 'trivia', text: 'Sahrami on painonsa mukaan maailman kallein mauste, koska se poimitaan käsin kukan luotista.' },
  { id: 't-102', category: 'trivia', text: 'Vanilja on toiseksi kallein mauste ja tulee orkidean pavusta.' },
  { id: 't-103', category: 'trivia', text: 'Suklaa on koirille myrkyllistä teobromiinin takia.' },
  { id: 't-104', category: 'trivia', text: 'Kahvipapu ei ole papu vaan kirsikkamaisen marjan siemen.' },
  { id: 't-105', category: 'trivia', text: 'Porkkanat olivat alun perin useimmiten violetteja.' },
  { id: 't-106', category: 'trivia', text: 'Omena kelluu, koska siitä noin neljännes on ilmaa.' },
  { id: 't-107', category: 'trivia', text: 'Hunajakenno on kuusikulmainen, koska se on tehokkain tapa täyttää pinta ilman hukkaa.' },
  { id: 't-108', category: 'trivia', text: 'Eiffel-torni kasvaa kesällä noin viisitoista senttimetriä lämpölaajenemisen takia.' },
  { id: 't-109', category: 'trivia', text: 'Nykyään käytössä oleva QWERTY-näppäimistö suunniteltiin kirjoituskoneen mekaniikan ehdoilla.' },
  { id: 't-110', category: 'trivia', text: 'Ensimmäinen tietokonevirhe eli bug oli kirjaimellisesti perhonen releen välissä.' },
  { id: 't-111', category: 'trivia', text: 'Ensimmäinen verkkosivu on yhä olemassa CERNin palvelimella.' },
  { id: 't-112', category: 'trivia', text: 'Sähköpostia lähetettiin ennen kuin internetiä oli olemassa nykymuodossaan.' },
  { id: 't-113', category: 'trivia', text: 'Suomessa on enemmän saaria kuin missään muussa maassa.' },
  { id: 't-114', category: 'trivia', text: 'Suomen järviä on lähes kaksisataatuhatta.' },
  { id: 't-115', category: 'trivia', text: 'Suomen kieli ei tee eroa hänen ja sen välillä sukupuolen suhteen.' },
  { id: 't-116', category: 'trivia', text: 'Islannissa ei ole yhtään hyttystä.' },
  { id: 't-117', category: 'trivia', text: 'Vatikaani on maailman pienin valtio.' },
  { id: 't-118', category: 'trivia', text: 'Venäjä ulottuu yhdentoista aikavyöhykkeen yli.' },
  { id: 't-119', category: 'trivia', text: 'Australiassa on enemmän kenguruja kuin ihmisiä.' },
  { id: 't-120', category: 'trivia', text: 'Sahara oli muutama tuhat vuotta sitten vihreä savanni.' },
  { id: 't-121', category: 'trivia', text: 'Kuolleessameressä ei voi upota, koska suolapitoisuus tekee vedestä niin tiheää.' },
  { id: 't-122', category: 'trivia', text: 'Kuolleenmeren pinta laskee vuosittain noin metrin.' },
  { id: 't-123', category: 'trivia', text: 'Maailman korkein vesiputous Angelin putous Venezuelassa on lähes kilometrin korkuinen.' },
  { id: 't-124', category: 'trivia', text: 'Mount Everest kasvaa muutaman millimetrin vuodessa.' },
  { id: 't-125', category: 'trivia', text: 'Merenpohjasta on kartoitettu tarkemmin pienempi osa kuin Marsin pinnasta.' },
  { id: 't-126', category: 'trivia', text: 'Tyynellämerellä on syvänne, joka on syvempi kuin Everest on korkea.' },
  { id: 't-127', category: 'trivia', text: 'Antarktis on maailman suurin aavikko sademäärällä mitattuna.' },
  { id: 't-128', category: 'trivia', text: 'Grönlanti näyttää kartalla Afrikan kokoiselta, mutta Afrikka on noin neljätoistakertainen.' },
  { id: 't-129', category: 'trivia', text: 'Islanti ja Grönlanti on nimetty osapuilleen päinvastoin kuin niiden ilmasto edellyttäisi.' },
  { id: 't-130', category: 'trivia', text: 'Suomen lippu vahvistettiin nykyiseen muotoonsa vuonna 1918.' },
  { id: 't-131', category: 'trivia', text: 'Oxfordin yliopisto on vanhempi kuin atsteekkien valtakunta.' },
  { id: 't-132', category: 'trivia', text: 'Kleopatra eli lähemmäs Kuu-lentoa kuin pyramidien rakentamista.' },
  { id: 't-133', category: 'trivia', text: 'Mammutteja eli vielä silloin kun Egyptin pyramideja rakennettiin.' },
  { id: 't-134', category: 'trivia', text: 'Hai on ollut olemassa pidempään kuin puut.' },
  { id: 't-135', category: 'trivia', text: 'Tyrannosaurus eli lähempänä nykyaikaa kuin Stegosaurusta.' },
  { id: 't-136', category: 'trivia', text: 'Ranska teloitti viimeisen kerran giljotiinilla samana vuonna kun Tähtien sota sai ensi-iltansa.' },
  { id: 't-137', category: 'trivia', text: 'Nintendo perustettiin vuonna 1889 pelikorttiyhtiönä.' },
  { id: 't-138', category: 'trivia', text: 'Kaksi tuntia kestänyt sota Britannian ja Sansibarin välillä vuonna 1896 on lyhin tunnettu sota.' },
  { id: 't-139', category: 'trivia', text: 'Napoleon ei ollut aikalaistensa mittapuulla lyhyt.' },
  { id: 't-140', category: 'trivia', text: 'Vanhin tunnettu asiakasvalitus on kirjoitettu savitaululle noin 3700 vuotta sitten.' },
  { id: 't-141', category: 'trivia', text: 'Kirjoitustaito keksittiin useaan kertaan toisistaan riippumatta eri puolilla maailmaa.' },
  { id: 't-142', category: 'trivia', text: 'Nolla otettiin lukuna käyttöön paljon myöhemmin kuin muut numerot.' },
  { id: 't-143', category: 'trivia', text: 'Roomalaisilla ei ollut merkkiä nollalle.' },
  { id: 't-144', category: 'trivia', text: 'Sekunnin pituus määritellään nykyään cesiumatomin värähtelyn perusteella.' },
  { id: 't-145', category: 'trivia', text: 'Metri määriteltiin alun perin osana Maan meridiaanin pituutta.' },
  { id: 't-146', category: 'trivia', text: 'Kilogramman määritelmä perustuu nykyään luonnonvakioon eikä metallikappaleeseen.' },
  { id: 't-147', category: 'trivia', text: 'Miljardi tarkoitti Britanniassa pitkään eri lukua kuin Yhdysvalloissa.' },
  { id: 't-148', category: 'trivia', text: 'Sekoitetussa korttipakassa oleva järjestys ei todennäköisesti ole koskaan aiemmin esiintynyt.' },
  { id: 't-149', category: 'trivia', text: 'Syntymäpäiväparadoksi: 23 ihmisen joukossa on jo yli puolet mahdollisuus samalle syntymäpäivälle.' },
  { id: 't-150', category: 'trivia', text: 'Taitettu paperi ei käytännössä taitu yli kahdeksaa kertaa, koska paksuus kaksinkertaistuu joka kerta.' },
  { id: 't-151', category: 'trivia', text: 'Shakissa on enemmän mahdollisia pelejä kuin havaittavassa maailmankaikkeudessa atomeja.' },
];
