/**
 * Domain model.
 *
 * The premise, stated once so the rest of the code can be read against it: this
 * app does not measure the user. It has one job — to be useful during the ten
 * minutes when the urge is loudest — and everything stored here exists to make
 * the *next* ten minutes easier, never to produce a verdict about the last ones.
 *
 * Consequences that show up throughout:
 *   - there is no streak, no score, no daily obligation, and nothing to keep up
 *   - `took` is recorded exactly as neutrally as `passed`, because an app you
 *     have to lie to stops receiving data at the moment data matters
 *   - every rate is about the *supply* ("did a walk help") rather than about the
 *     person ("did you succeed")
 */

/** What the drink would do, asked forward — to choose a substitute, not to file a report. */
export type BuiltinDemand =
  | 'settle' // rauhoittua
  | 'detach' // irrota päivästä
  | 'company' // olla ihmisten kanssa
  | 'sleep' // nukahtaa
  | 'empty' // täyttää tyhjä ilta
  | 'feel-less'; // tuntea vähemmän

export const BUILTIN_DEMANDS: BuiltinDemand[] = [
  'settle',
  'detach',
  'company',
  'sleep',
  'empty',
  'feel-less',
];

/**
 * A demand key: a builtin, or a user-defined id.
 *
 * Widened to `string` for the same reason as everything else here — six shipped
 * options are a guess, and a guess that misses makes the user pick the nearest
 * wrong one, after which their prepared responses are filed against a need they
 * do not have.
 */
export type Demand = string;

export const CUSTOM_DEMAND_PREFIX = 'own:';

export const isCustomDemand = (d: Demand): boolean => d.startsWith(CUSTOM_DEMAND_PREFIX);

/** A need the user named themselves. Archived rather than deleted, so history stays readable. */
export interface CustomDemand {
  id: Demand;
  label: string;
  createdAt: number;
  archived?: boolean;
}

/**
 * Something concrete the user prepared in advance for a given need.
 *
 * Written calm, offered hot. Nothing here is generated by the app: at the moment
 * it matters, a suggestion from software has no standing, and the user's own
 * sentence does.
 */
export interface Supply {
  id: string;
  label: string;
  /** Which needs this is meant for. */
  demands: Demand[];
  /** Outcomes of past offers, oldest first. */
  attempts: SupplyAttempt[];
  archived?: boolean;
  createdAt: number;
}

export interface SupplyAttempt {
  at: number;
  demand: Demand;
  /** Did it help with the need — not whether the user stayed dry afterwards. */
  helped: boolean;
}

export type Outcome =
  /** Meni ohi. */
  | 'passed'
  /** Otin sen. Recorded without comment. */
  | 'took'
  /** The user never came back to say. Never guessed at. */
  | 'unknown';

/**
 * One urge, from the moment the button was pressed.
 *
 * `waitedMs` is stored explicitly rather than derived from timestamps, because
 * the interesting quantity is how long the user actually held on — which is not
 * the same as wall-clock time between two events if the phone was put down.
 */
export interface Episode {
  id: string;
  startedAt: number;
  demand: Demand;
  /** The supply offered, if the user had one prepared for this need. */
  supplyId?: string;
  /** How long the wait ran before the episode closed. */
  waitedMs: number;
  /** How many times the user chose to keep waiting. */
  extensions: number;
  outcome: Outcome;
  /** Set when the episode closes; absent while it is still running. */
  endedAt?: number;
}

export interface Settings {
  /** Length of the first wait. */
  waitMs: number;
  /** Added by "hetki lisää". */
  extensionMs: number;
  /**
   * Whether the reading panel opens by itself during a wait.
   *
   * Remembered rather than asked each time: someone who wants something to read
   * at 23:00 wants it every time, and someone who finds it intrusive should not
   * have to decline it twice.
   */
  factsOn: boolean;
  /** Seconds each line stays before the next one fades in. */
  factSeconds: number;
  /**
   * Mix the useless-knowledge corpus into the reading.
   *
   * Opt-in: someone who opened this to read about alcohol should not have
   * octopus hearts arrive unasked. Someone who wants distraction rather than
   * information can have it in one tap.
   */
  triviaOn: boolean;
}

export const DEFAULT_SETTINGS: Settings = {
  waitMs: 10 * 60 * 1000,
  extensionMs: 5 * 60 * 1000,
  // Off by default. Reading is an offer, not something that starts talking at
  // someone who opened the app to hold on for ten minutes.
  factsOn: false,
  factSeconds: 9,
  triviaOn: false,
};
